spring:
  application:
    name: vblog
  datasource:
    username: root
    password: 123zxc
    url: jdbc:mysql:///blog?serverTimezone=UTC
  mail: # MailProperties
    host: smtp.163.com
    port: 465
    username: liuzhaoyang94@163.com
    password: blog551253
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 11
    host: 192.168.134.142
    port: 6379
    password:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: test-consumer-group
#      enable-auto-commit: true
#      auto-commit-interval: 3000
#  data:
#    elasticsearch:
#      cluster-name: vi3blog
#      cluster-nodes: 127.0.0.1:9300
  mvc:
    static-path-pattern: /static/**

server:
  servlet:
    context-path: /vblog
logging:
  level:
    com.vi3nty.blog.mapper: debug
blog:
  path:
    domain: http://localhost:8080
